name: Publish Python Package

on:
  release:
    types: [created]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PACKAGE_API_ID }}
        TWINE_PASSWORD: ${{ secrets.PACKAGE_API_SECRET }}
      run: |
        python -m build python-packages/core
        twine upload python-packages/core/dist/*
        
        python -m build python-packages/extensions
        twine upload python-packages/extensions/dist/*
        
        python -m build python-packages/hydra
        twine upload python-packages/hydra/dist/*
        
        python -m build python-packages/lokki
        twine upload python-packages/lokki/dist/*
        
        python -m build python-packages/arjun
        twine upload python-packages/arjun/dist/*
        
        python -m build python-packages/matel
        twine upload python-packages/matel/dist/*

