name: Pylint
on:
  push:
    paths:
      - '**.py'
    branches:
      - main
      - 'ver_*'
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        pip install -r python-packages/core/requirements.txt
    - name: Lint core package source with pylint
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pylint python-packages/core --max-line-length=127 --disable=R0801 --exit-zero
    - name: Lint extensions with pylint
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pylint python-packages/extensions --max-line-length=127 --disable=R0801 --exit-zero